# Generated by Django 4.0.1 on 2022-06-12 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address_model',
            fields=[
                ('id_add', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('addre', models.TextField()),
            ],
        ),
    ]
